export default {
	PYTHON_ALIAS: 'python', //python3
	SERVER_HTTP_PORT: 3_000,
	SERVER_HTTPS_PORT: 443,
	TLS_FOLDER_PATH: './tls',
	TLS_KEY_FILENAME: 'key.pem',
	TLS_CERT_FILENAME: 'cert.pem',
	PROCESSING_TIMEOUT: 10_000,
	COOKIE_CLIENT_ID_LIFE_DAYS: 7,
	AI_MODEL_FOLDER_PATH: './aimodel',
	PYTHON_CONNECTOR_FILENAME: 'predictor.py',
	MAX_THREADS: 4
}